version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: site-builder-db
    ports:
      - "5433:5432"
    env_file:
      - .env.local
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres: